update 2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,6 +47,26 @@ jobs:
             echo "✅ Node.js app stopped"
           ENDSSH
 
+          # Restart backend on server
+          ssh -p 21098  -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'
+
+            source /home/alottpil/nodevenv/irelandmuslimsapi.alotaki.com/14/bin/activate && cd /home/alottpil/irelandmuslimsapi.alotaki.com
+            npm install --omit=dev
+
+            # Stop the app (if any old process is running) and start it again
+            pkill -f "node index.js" || true
+            nohup node index.js > out.log 2>&1 &
+
+            # Check if the Node.js process is running
+            sleep 5  # Wait for a few seconds to allow the process to start
+            if pgrep -f "node index.js" > /dev/null; then
+              echo "✅ Node.js app successfully restarted"
+            else
+              echo "❌ Failed to start Node.js app"
+              exit 1
+            fi
+          ENDSSH
+
           # Start Node.js app using CloudLinux command
           ssh -p 21098 -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'ENDSSH'
             cloudlinux-selector start --json --interpreter nodejs --user alottpil --app-root /home/alottpil/irelandmuslimsapi.alotaki.com
